[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
# rps_endpoints = { sepolia-eth = "", arb-sepolia = "" }
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@ccip/=lib/ccip/",
]

[lint]
exclude_lints = [
    "screaming-snake-case-immutable", 
    "mixed-case-variable", 
    "screaming-snake-case-const",
    "erc20-unchecked-transfer",
    "@chainlink-local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
