[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@ccip/contracts=lib/chainlink-ccip/chains/evm/contracts/"
]

[lint]
exclude_lints = [
    "screaming-snake-case-immutable", 
    "mixed-case-variable", 
    "screaming-snake-case-const"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
